kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: generic-app
  annotations:
    openshift.io/display-name: "Generic App"
    description: "A simple generic application"
    iconClass: "icon-play"
    tags: "app"
parameters:
  - name: IMAGE_NAME
    description: The name of the container image
  - name: IMAGE_TAG
    description: The tag of the container image
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: generic-app
      labels:
        app: generic-app
        app.kubernetes.io/component: generic-app
        app.kubernetes.io/instance: generic-app
        app.kubernetes.io/name: generic-app
        app.kubernetes.io/part-of: generic-app
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: generic-app
      template:
        metadata:
          labels:
            app: generic-app
            deployment: generic-app
        spec:
          containers:
            - name: generic-app
              image: ${IMAGE_NAME}:${IMAGE_TAG}
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
          revisionHistoryLimit: 10
          progressDeadlineSeconds: 600
  - kind: Service
    apiVersion: v1
    metadata:
      name: generic-app
      labels:
        app: generic-app
        app.kubernetes.io/component: generic-app
        app.kubernetes.io/instance: generic-app
        app.kubernetes.io/name: generic-app
        app.kubernetes.io/part-of: generic-app
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      internalTrafficPolicy: Cluster
      type: ClusterIP
      sessionAffinity: None
      selector:
        app: generic-app
        deployment: generic-app
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: generic-app
      labels:
        app: generic-app
        app.kubernetes.io/component: generic-app
        app.kubernetes.io/instance: generic-app
        app.kubernetes.io/name: generic-app
        app.kubernetes.io/part-of: generic-app
    spec:
      to:
        kind: Service
        name: generic-app
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
