apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamltest1
  labels:
    app: yamltest1
name: yamltest1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yamltest1
  template:
    metadata:
      labels:
        app: yamltest1
    spec:
      containers:
      - name: yamltest1
        image: ghcr.io/magicman77/nginx-unprivileged:v1
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: yamltest1
  labels:
    app: yamltest1
spec:
  selector:
    app: yamltest1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yamltest1
spec:
  to:
    kind: Service
    name: yamltest1
  port:
    targetPort: 8080
  tls:
    termination: edge