apiVersion: apps/v1
kind: Deployment
metadata:
  name: yanistest2
  labels:
    app: yanistest2
    app.kubernetes.io/component: yanistest2
    app.kubernetes.io/instance: yanistest2
    app.kubernetes.io/name: yanistest2
    app.kubernetes.io/part-of: yanistest2
    app.openshift.io/runtime: httpd
    app.openshift.io/runtime-version: 2.4-el7  
name: yanistest2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yanistest2
  template:
    metadata:
      labels:
        app: yanistest2
    spec:
      containers:
      - name: yanistest2
        image: ghcr.io/magicman77/nginx-unprivileged:v1
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: yanistest2
  labels:
    app: yanistest2
    app.kubernetes.io/component: yanistest2
    app.kubernetes.io/instance: yanistest2
    app.kubernetes.io/name: yanistest2
    app.kubernetes.io/part-of: yanistest2
    app.openshift.io/runtime: httpd
    app.openshift.io/runtime-version: 2.4-el7
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/BBHE11/auftrag6.git'
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  selector:
    app: yanistest2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yanistest2
spec:
  to:
    kind: Service
    name: yanistest2
  port:
    targetPort: 8080
  tls:
    termination: edge