# Verwenden Sie das offizielle Nginx-Image als Basis
FROM nginx

# Kopieren Sie die HTML-Datei in den Container
COPY index.html /usr/share/nginx/html/ 

# Port 80 für den Container freigeben
EXPOSE 80
