kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
        tier: database
    spec:
      volumes:
        - name: mysqlvolume
          persistentVolumeClaim:
            claimName: mysqlvolume
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: mysqlvolume
              mountPath: /var/lib/mysql
          terminationMessagePolicy: File
          image: mariadb
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpmyadmin
        deployment: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: bitnami/phpmyadmin
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          env:
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-password
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: quotes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quotes
    spec:
      containers:
        - name: quotes
          image: 'quay.io/donschenck/quotes:v2'
          ports:
            - containerPort: 10000
              protocol: TCP
          env:
            - name: DB_SERVICE_NAME
              value: mysql
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: quotesweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotesweb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quotesweb
    spec:
      containers:
        - name: quotes
          image: 'quay.io/donschenck/quotesweb:v1'
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---

kind: Secret
apiVersion: v1
metadata:
  name: mysql
data:
  database-password: YWRtaW4=
  database-user: cm9vdA==
type: Opaque
---

kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  clusterIP: 172.30.2.166
  ipFamilies:
    - IPv4
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.2.166
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: mysql
    tier: database
---

kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin
spec:
  clusterIP: 172.30.181.98
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.181.98
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: phpmyadmin
    deployment: phpmyadmin
---

kind: Service
apiVersion: v1
metadata:
  name: quotes
spec:
  clusterIP: 172.30.86.214
  ipFamilies:
    - IPv4
  ports:
    - name: 10000-tcp
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.86.214
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: quotes
---

kind: Service
apiVersion: v1
metadata:
  name: quotesweb
spec:
  clusterIP: 172.30.249.240
  ipFamilies:
    - IPv4
  ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.249.240
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: quotesweb
---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: phpmyadmin
spec:
  host: phpmyadmin-zlic-lpfyl1.apps.exoscale-ch-gva-2-0.appuio.cloud
  to:
    kind: Service
    name: phpmyadmin
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quotes
spec:
  host: quotes-zlic-lpfyl1.apps.exoscale-ch-gva-2-0.appuio.cloud
  to:
    kind: Service
    name: quotes
    weight: 100
  port:
    targetPort: 10000-tcp
  wildcardPolicy: None
---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quotesweb
spec:
  host: quotesweb-zlic-lpfyl1.apps.exoscale-ch-gva-2-0.appuio.cloud
  to:
    kind: Service
    name: quotesweb
    weight: 100
  port:
    targetPort: 3000-tcp
  wildcardPolicy: None