apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: qotd
  labels:
    app: qotd
spec:
  selector:
    app: qotd
  replicas: 1
  template:
    metadata:
      labels:
        app: qotd
    spec:
      containers:
        - name: qotd
          image: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/qotd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
              protocol: TCP
  triggers:
  - type: ConfigChange 
  - imageChangeParams:
      automatic: true
      containerNames:
      - qotd
      from:
        kind: ImageStreamTag
        name: qotd:latest
    type: ImageChange
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: quotes
    sandbox: learn-kubernetes
    learn-kubernetes: quotes
  name: quotes
spec:
  ports:
  - name: 10000-tcp
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: quotes
  sessionAffinity: None
  type: ClusterIP
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: quotes
    sandbox: learn-kubernetes
    learn-kubernetes: quotes
  name: quotes
spec:
  port:
    targetPort: 10000-tcp
  to:
    kind: Service
    name: quotes